### ISSUE TITLE
Any instructions for running the code?

### ISSUE THREAD

**Issue by lixin4ever** [mprompting/xlmrprompt#1]
Hi Mengjie,  thanks for sharing this project. Would you mind providing additional instructions or guidance in README so that we can re-run your code?

**Comment by joemzhao** [comment]
hi @lixin4ever, thanks for your interest! i've pushed some scripts, pls c.f. https://github.com/mprompting/xlmrprompt/commit/28e4b38d3caf766633954636190e3a05767b285e

there might be a few adjustments need to be adapted, e.g., pointing to the few-shot dataset directory :)

**Comment by qiuxiaoyu9954** [comment]
Hi Mengjie, I would like to ask, is the validation set used before transferring from English to other languages also in English?
